name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # or your default branch

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      # Configurar Node.js usando la versión @v4 (con Node 20)
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      # Instalar dependencias
      - name: Install dependencies
        run: npm install

      # Compilar el proyecto
      - name: Build
        run: npm run build -- --prod --base-href="/barbershop-appointment-app-ionic-angular/"

      # Desplegar a GitHub Pages usando peaceiris/actions-gh-pages
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist/barber-shop  # Ajusta si tu carpeta de salida es diferente (por ejemplo, "www" en proyectos Ionic)
